### ISSUE TITLE
Monitor Transaction Error

### ISSUE THREAD

**Issue by wip-abramson** [BlackMac/ostkit.js#4]
Hi,

I keep getting an unhandled promise rejection when I monitor my transaction status.

(node:18372) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at res.transactions.forEach.transaction (/home/will/TheCommunityMind/server/node_modules/ostkit/lib/ostkit.js:33:78)
    at Array.forEach (<anonymous>)
    at transactiontypesStatus.then.res (/home/will/TheCommunityMind/server/node_modules/ostkit/lib/ostkit.js:32:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:18372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 674)

The transaction still completes so not a big issue just wondered if I am doing something wrong. Happy to help fix it if needed.

Thanks,
Will

**Comment by wip-abramson** [comment]
I think it may have been because I was not using stopMonitoringTransaction()

**Comment by wip-abramson** [comment]
Actually, no its not that. Exceptions are not getting caught somewhere and it often causes my node server to get stuck in a callback loop.
